### ISSUE TITLE
README.md: incorrect commands in quickstart section?

### ISSUE THREAD

**Issue by stardust85** [Klowner/docker-gitlab-mirrors#1]
Hi,

I'm new to docker and I'm trying to use this. 

I tried this command with docke 1.7.1

```
[root@vagrant gitlab]# docker run --rm -it \
   -v ${PWD}:/config:/config \
   quay.io/klowner/gitlab-mirrors:latest \
   run ssh git.example.com
```

and got "Error response from daemon: invalid mode for volumes-from: /config"

I checked docker engine docs and it really doesn't expect path as third part after last colon. It expects option. The format should be src:dest:options.

**Comment by Klowner** [comment]
Whoops, you're absolutely right, that's a typo.

Should be `-v "${PWD}/config:/config"`

**Comment by Klowner** [comment]
Sorry about that! Welcome to Docker :whale:

I always got confused by the `-v` syntax initially, but it's `-v /path/on/host:/path/inside/container`, there are some options for a 3rd parameter for read-only mounts like `-v /host:/container:ro`.

💃

**Comment by stardust85** [comment]
Thanks for the quick fix. Now it all makes sense :) Btw, Where did you get the docker icon in your last comments, it's awesome :)

**Comment by Klowner** [comment]
Very welcome.

It's just a `:whale:` 🐳

**Comment by stardust85** [comment]
Please fix also the first example. There is still ${PWD}:some/path instead ${PWD}/some/path. I'd send a PR but I'm busy now...

**Comment by Klowner** [comment]
Whoops, missed that one.
