### ISSUE TITLE
the example script doesn't work in cron

### ISSUE THREAD

**Issue by stardust85** [Klowner/docker-gitlab-mirrors#3]
First, in the script we shouldn't rely on ${PWD}, we should use the absolute path.
Second, the -t option should be removed so it works in cron. When -t is there, I get the following error when run in cron:

```
docker run --rm -it -v /opt/gitlab/mirror/config:/config -v /opt/gitlab/mirror/mirrors:/data/Mirrors -e GITLAB_MIRROR_GITLAB_UID=0 -e GITLAB_MIRROR_GITLAB_USER=gitmirror -e GITLAB_MIRROR_GITLAB_NAMESPACE=Mirrors -e GITLAB_MIRROR_GITLAB_URL=**** quay.io/klowner/gitlab-mirrors:latest update test_repo
cannot enable tty mode on non tty input
```

**Comment by stardust85** [comment]
When removed -t, it started to work. And it works also in normal command line (without cron).

**Comment by Klowner** [comment]
Yes, you should use an absolute path. As a person writing an example, I can't make assumptions about what path would be like, look into your heart and find the path that the universe shows you, only the universe in its ultimate power can show one the absolute path. 

As for the `-t` I can get rid of that :+1:
