### ISSUE TITLE
There was an unknown issue with manage_gitlab_project.py

### ISSUE THREAD

**Issue by Microbenefits** [Klowner/docker-gitlab-mirrors#6]
when I add mirror ,meet this error, please help, thanks.

docker-compose run --rm gitlab-mirrors add --git --project-name Test --mirror git@git.domain.com:/Test/test.git
Resolving gitlab remote.
Creating new project Test
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 105, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 78, in createproject
    git.add_project(pname,description=description,**project_options)
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 184, in fn
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 418, in _post
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 435, in _request
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 411, in _check_status_code
gitlab3.exceptions.MissingRequiredAttribute: URL: http://git.domain.cn/api/v3/projects, Data: {'wall_enabled': 'false', 'namespace_id': '4', 'snippets_enabled': 'false', 'merge_requests_enabled': 'false', 'name': 'Test', 'issues_enabled': 'false', 'wiki_enabled': 'false', 'public': 'false', 'description': 'Mirror of git@git.domain.com:/Test/test.git'}
There was an unknown issue with manage_gitlab_project.py

I'm trying mirror project from remote gitlab to local gitlab
remote gitlab verson:8.8.5
local gitlab verson:8.8.5

**Comment by Klowner** [comment]
I'll try to take a look at this today.

You should really also update your Gitlab, 8.8.5 is over two years old.

**Comment by Klowner** [comment]
Please try image `quay.io/klowner/gitlab-mirrors:0.5.4pre`

**Comment by Microbenefits** [comment]
Thanks, Iet me try it.



ricky.liu@microbenefits.com
 
From: Mark Riedesel
Date: 2018-05-16 00:01
To: Klowner/docker-gitlab-mirrors
CC: Microbenefits; Author
Subject: Re: [Klowner/docker-gitlab-mirrors] There was an unknown issue with manage_gitlab_project.py (#6)
Please try image quay.io/klowner/gitlab-mirrors:0.5.4pre

**Comment by fhaefemeier** [comment]
The issue is since Gitlab V11 api V3 is no longer available (https://docs.gitlab.com/ce/api/v3_to_v4.html). Are there any plans to move to api V4?

**Comment by fhaefemeier** [comment]
Sorry, I didn't saw the development branch which use V4. I test it (docker 0.5.4.pre) and it works. I can now create new mirrors. But I used env.-var. GITLAB_MIRROR_NEW_PUBLIC="true" to make the project public. But this is not working. The new created project in GItlab is 'internal'.

**Comment by Klowner** [comment]
Ah, I bet I missed that parameter if it's a new one, probably just an issue of adding it to the others. I'll check it out, otherwise PR's are welcome!

**Comment by Microbenefits** [comment]
I have solved the issue through Gitlab v11.0.2，thanks.

**Comment by Klowner** [comment]
I've opened a new ticket #7 with your issue, @fhaefemeier
